POST http://localhost:3000/accounts
Content-Type: application/json

{
    "email": "raffigo.toto@thales.evotec",
    "password": "password123"
}

POST http://localhost:3000/accounts
Content-Type: application/json

{
    "email": "raffigo.totothales.evotec",
    "password": "password123!"
}


POST http://localhost:3000/accounts
Content-Type: application/json

{
    "email": "raffigo.toto@thales.evotec",
    "password": "password123!"
}